id: airbyte-sync
namespace: company.team
tasks:
  - id: data_ingestion
    type: io.kestra.plugin.airbyte.connections.Sync
    connectionId: e3b1ce92-547c-436f-b1e8-23b6936c12ab
    url: http://host.docker.internal:8000/
    username: "{{ secret('AIRBYTE_USERNAME') }}"
    password: "{{ secret('AIRBYTE_PASSWORD') }}"
triggers:
  - id: every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"
extend:
  title: Trigger a single Airbyte sync on schedule
  description: >
    This flow will sync data using Airbyte on schedule.


    It's best to provide Airbyte server credentials (the `username` and
    `password`) as secrets, but you can also paste them in plain text during
    testing.
  tags:
    - Ingest
    - Schedule
  ee: false
  demo: false
  meta_description: This flow will sync data using Airbyte.
