id: create-jira-ticket-on-failure
namespace: company.team

tasks:
  - id: create_ticket
    type: io.kestra.plugin.jira.issues.Create
    baseUrl: your-domain.atlassian.net
    username: your_email@example.com
    password: "{{ secret('JIRA_API_TOKEN') }}"
    projectKey: myproject
    summary: Kestra Workflow Failed
    description: "{{ trigger.executionId }} has failed on {{ taskrun.startDate }}"
    labels:
      - bug
      - workflow

triggers:
  - id: on_failure
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.plugin.core.condition.ExecutionNamespaceCondition
        namespace: company
        comparison: PREFIX

extend:
  title: Create a ticket in Jira when a workflow fails
  description: >-
    This system flow will create a ticket in Jira anytime a workflow in a
    `company` namespace (or any nested child namespace) fails. 

    Using this pattern, you can track your Kestra workflow execution incidents
    alongside other tickets in Jira.

    You can customize that system flow by modifying the task, adding more tasks
    to the flow or adjusting the trigger conditions. Read more about that
    pattern in the [Administrator
    Guide](https://kestra.io/docs/administrator-guide/monitoring).

    Let's create a flow in the namespace with prefix `company` that will always
    fail.

    ```yaml
    id: failure_flow
    namespace: company.team

    tasks:
      - id: always_fails
        type: io.kestra.plugin.core.execution.Fail
    ```

    Whenever you run the `failure_flow`, it will trigger an execution of the
    `create_jira_ticket_on_failure` flow. As a result, a new ticket will be
    created in Jira helping you track failed workflows interacting with customer
    data alongside other customer tickets.
  tags:
    - System
    - Notifications
  ee: false
  demo: false
  meta_description: Create a Jira ticket when a workflow processing customer data fails
