id: every-monday
namespace: company.team

tasks:
  - id: log_trigger_or_execution_date
    type: io.kestra.plugin.core.log.Log
    message: "{{ trigger.date ?? execution.startDate }}"

triggers:
  - id: first_monday_of_the_month
    type: io.kestra.plugin.core.trigger.Schedule
    timezone: Europe/Berlin
    cron: 0 11 * * MON
    conditions:
      - type: io.kestra.plugin.core.condition.DayWeekInMonth
        date: "{{ trigger.date }}"
        dayOfWeek: MONDAY
        dayInMonth: FIRST

extend:
  title: Run a flow on the first Monday of each month at 11 AM
  description: This flow will run only on the first Monday of each month at 11 AM.
  tags:
    - Schedule
    - Trigger
    - Variables
  ee: false
  demo: true
  meta_description: "This flow will run only on the first Monday of each month at
    9 AM. Before starting the regularly scheduled runs, Kestra will first
    execute runs for the past intervals from the `start` date until the current
    date."
