id: flow-condition-not
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Demo for Not condition 

triggers:
  - id: flow_condition
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.Not
        conditions:
          - type: io.kestra.plugin.core.condition.ExecutionNamespace
            namespace: company.analytics
            comparison: PREFIX
extend:
  title: Executes flow on flow trigger with Not condition
  description: >-
    This trigger executes the flow with the flow condition that the executed 
    flow that triggers this flow can be from any namespace except those 
    prefixed with `company.analytics`.

    With the Not condition, you can put a negation of the condition. In the given flow, we 
    are negating the condition the executed flow belongs to `company.analytics` namespace 
    prefix.

    The Not condition can be used along with both Schedule and Flow triggers.

  tags:
    - Trigger
  ee: false
  demo: true
  meta_description: This flow executes on flow trigger with Not condition.
