id: flow-downstream
namespace: company.team

tasks:
  - id: task_c
    type: io.kestra.plugin.core.debug.Return
    format: "{{ task.id }}"

triggers:
  - id: multiple_listen_flow
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - SUCCESS
      - id: multiple
        type: io.kestra.plugin.core.condition.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          flow_a:
            type: io.kestra.plugin.core.condition.ExecutionFlow
            namespace: company.team
            flowId: flow_a
          flow_b:
            type: io.kestra.plugin.core.condition.ExecutionFlow
            namespace: company.team
            flowId: flow_b

extend:
  title: Trigger a flow when other flows finish successfully
  description: "Trigger a flow as soon as two other flows finish successfully.
    This flow will be triggered when `flow_a` and `flow_b` both successfully
    finish their execution within the time window of 24 hours (`window: P1D` = 1
    day) from now (`windowAdvance: P0D` = zero days)."
  tags:
    - Trigger
  ee: false
  demo: false
  meta_description: Trigger a flow as soon as two other flows finish successfully.
    This flow will be triggered when `flow_a` and `flow_b` both successfully
    finish their execution within the time window of 24 hours.
