id: schedule-condition-dayweek
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Demo for DayWeek condition 

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 11 * * *"
    conditions:
      - type: io.kestra.plugin.core.condition.DayWeek
        date: "{{ trigger.date }}"
        dayOfWeek: "MONDAY"

extend:
  title: Executes flow on schedule trigger with DayWeek condition
  description: >-
    This flow triggers the task at 11am every day with the schedule condition that 
    the trigger date is a Monday.

    With DayWeek condition, you can enforce the condition for the flow to run on 
    only a particular day of the week.
  tags:
    - Schedule
    - Trigger
  ee: false
  demo: true
  meta_description: This flow executes on schedule trigger with DayWeek condition.
