id: schedule-condition-dayweekinmonth
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Demo for DayWeekInMonth condition 

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 11 * * *"
    conditions:
      - type: io.kestra.plugin.core.condition.DayWeekInMonth
        date: "{{ trigger.date }}"
        dayOfWeek: SATURDAY
        dayInMonth: LAST

extend:
  title: Executes flow on schedule trigger with DayWeekInMonth condition
  description: >-
    This trigger executes the flow at 11am every day with the schedule condition that the 
    trigger date should fall on the last Saturday of the month. Hence, the flow will 
    actually run only once in a month, i.e. on the last Saturday of the month at 11am.

    With DayWeekInMonth condition, you can enforce the condition for the flow to run on 
    only a particular day of the week relative to the current month.

  tags:
    - Schedule
    - Trigger
  ee: false
  demo: true
  meta_description: This flow executes on schedule trigger with DayWeekInMonth condition.
