id: schedule-condition-weekend
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Demo for Weekend condition 

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 11 * * *"
    conditions:
      - type: io.kestra.plugin.core.condition.Weekend

extend:
  title: Executes flow on schedule trigger with Weekend condition
  description: >-
    This trigger executes the flow at 11am every day with the schedule condition that the 
    trigger date should fall on a weekend, i.e. either on a Saturday or a Sunday.

    With the Weenkend condition, you can enforce the condition for the flow to execute 
    only on a weekend.
  tags:
    - Schedule
    - Trigger
  ee: false
  demo: true
  meta_description: This flow executes on schedule trigger with Weekend condition.
