id: taxi-trip-data
namespace: company.team
tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: running backfill for file
      https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{{
      trigger.date ?? execution.startDate | date("yyyy-MM") }}.parquet
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 8 1 * *
    timezone: US/Eastern
    backfill:
      start: 2023-01-01T00:00:00Z
extend:
  title: Backfill a flow for the Yellow Taxi Trip dataset
  description: >-
    To backfill a flow, add a `start` date from which Kestra should backfill the
    past runs before running the regular schedule.


    The expression `{{ trigger.date ?? execution.startDate | date("yyyy-MM") }}`
    will always give you the execution date regardless of whether you triggered
    the flow ad-hoc or whether it ran based on a schedule. The date function
    formats the date according to the provided date template.
  tags:
    - Schedule
    - Variables
  ee: false
  demo: true
  meta_description: This workflow is an template to backfill a flow.
