id: ai-learning-roadmap-n8n
namespace: company.team

triggers:
  - id: prompt
    type: io.kestra.plugin.core.trigger.Webhook
    key: prompt

inputs:
  - name: prompt
    type: STRING
    description: Natural language learning request
    defaults: I want to learn Kubernetes in 60 days with hands-on practice

tasks:
  - id: call_n8n
    type: io.kestra.plugin.n8n.webhook.TriggerWorkflow
    method: POST
    uri: "{{ secret('N8N_WEBHOOK_URL') }}"
    body:
      prompt: "{{ inputs.prompt }}"

  - id: validate_roadmap
    type: io.kestra.plugin.scripts.python.Script
    outputFiles:
      - roadmap.json
    script: |
      import json

      raw = """{{ outputs.call_n8n.body }}"""
      roadmap = json.loads(raw)

      if not isinstance(roadmap, list):
          raise ValueError("Expected a JSON array of roadmap entries")

      required_keys = {"day", "focus", "topics", "practice", "outcome"}
      for item in roadmap:
          if not required_keys.issubset(item):
              raise ValueError(f"Invalid roadmap item: {item}")

      with open("roadmap.json", "w") as f:
          json.dump(roadmap, f, indent=2)

  - id: create_csv
    type: io.kestra.plugin.scripts.python.Script
    inputFiles:
      roadmap.json: "{{ outputs.validate_roadmap.outputFiles['roadmap.json'] }}"
    outputFiles:
      - learning-roadmap.csv
    script: |
      import json
      import pandas as pd

      with open("roadmap.json") as f:
          roadmap = json.load(f)

      for item in roadmap:
          item["status"] = "Pending"

      df = pd.DataFrame(roadmap)
      df.to_csv("learning-roadmap.csv", index=False)

extend:
  title: AI Learning Roadmap Generator with n8n
  description: |
    This Blueprint demonstrates how to orchestrate an AI-assisted
    learning roadmap using Kestra together with n8n.

    A user submits a learning request in plain language. Kestra
    receives the request and triggers an n8n workflow, where Gemini
    converts it into a structured roadmap. Kestra then validates
    the response and exports the result as a CSV file.

    This approach is useful when AI is used for planning or suggestions,
    while execution, validation, and outputs remain fully controlled
    by Kestra.

    Prerequisites:
      - Secrets:
        - N8N_WEBHOOK_URL: Webhook URL of the n8n workflow returning roadmap JSON.
      - Services:
        - An n8n instance with Gemini configured.

    Expected outputs:
      - learning-roadmap.csv: CSV file containing the learning plan.

  tags:
    - AI
  ee: false
  demo: false
  meta_description: Generate a learning roadmap using Kestra and n8n.

