id: ai-learning-roadmap-n8n
namespace: blueprints.education

extend:
  title: AI-Powered Learning Roadmap Generator with n8n
  description: |
    This Blueprint demonstrates how to orchestrate an AI-powered planning
    workflow using Kestra together with n8n.

    Kestra acts as the initiator and controller of the workflow, while n8n
    uses Gemini to transform a natural-language learning prompt into a
    structured learning roadmap. Kestra then validates the AI-generated
    response and produces an Excel roadmap artifact that can be downloaded
    or shared.

    Prerequisites:
      - Secrets:
        - N8N_WEBHOOK_URL: Webhook URL of an n8n workflow configured to call Gemini
      - Services:
        - A running n8n instance with Gemini configured

    Expected outputs:
      - learning-roadmap.xlsx: An Excel file containing a day-by-day learning plan

    Notes:
      - The n8n workflow must return strict JSON only.
      - Any markdown or explanatory text in the AI response will cause validation to fail.

  tags:
    - AI
    - Education
    - Automation
    - Orchestration
    - n8n
    - Demo

  ee: false
  demo: true
  meta_description: Generate an AI-powered learning roadmap using Kestra orchestration and n8n.

description: >
  Orchestrate an AI-assisted learning roadmap workflow using Kestra and n8n.

triggers:
  - id: prompt
    type: io.kestra.plugin.core.trigger.Webhook
    key: prompt

inputs:
  - name: prompt
    type: STRING
    description: Natural language learning request
    defaults: I want to learn Kubernetes in 60 days with hands-on practice

tasks:
  - id: log_prompt
    type: io.kestra.plugin.core.log.Log
    description: Log the user prompt for observability and debugging
    message: |
      User prompt:
      {{ inputs.prompt }}

  - id: call_n8n
    type: io.kestra.plugin.core.http.Request
    description: Call an n8n workflow that uses Gemini to generate a roadmap
    method: POST
    uri: "{{ secret('N8N_WEBHOOK_URL') }}"
    headers:
      Content-Type: application/json
    body: |
      {
        "prompt": "{{ inputs.prompt }}"
      }

  - id: validate_roadmap
    type: io.kestra.plugin.scripts.python.Script
    description: Validate the AI-generated roadmap JSON and persist it as a file
    dependencies:
      - kestra
    outputFiles:
      - roadmap.json
    script: |
      import json

      raw = """{{ outputs.call_n8n.body }}"""
      roadmap = json.loads(raw)

      if not isinstance(roadmap, list):
          raise ValueError("Expected a JSON array of roadmap entries")

      required_keys = {"day", "focus", "topics", "practice", "outcome"}
      for item in roadmap:
          if not required_keys.issubset(item):
              raise ValueError(f"Invalid roadmap item: {item}")

      with open("roadmap.json", "w") as f:
          json.dump(roadmap, f, indent=2)

  - id: create_excel
    type: io.kestra.plugin.scripts.python.Script
    description: Convert the validated roadmap JSON into an Excel file
    dependencies:
      - pandas
    inputFiles:
      roadmap.json: "{{ outputs.validate_roadmap.outputFiles['roadmap.json'] }}"
    outputFiles:
      - learning-roadmap.xlsx
    script: |
      import json
      import pandas as pd

      with open("roadmap.json") as f:
          roadmap = json.load(f)

      for item in roadmap:
          item["status"] = "Pending"

      df = pd.DataFrame(roadmap)
      df.to_excel("learning-roadmap.xlsx", index=False)
