id: ai-news-summary-notion-perplexity
namespace: company.team

tasks:
  - id: chat_completion
    type: io.kestra.plugin.perplexity.ChatCompletion
    apiKey: "{{ secret('PERPLEXITY_API_KEY') }}"
    model: sonar
    messages:
      - type: USER
        content: "Can you compile a list of the most important news for today for a person living in Berlin, Germany? Please respond with a bulleted list of headline and a hyperlink to the text all as markdown."
    temperature: 0.7
  - id: create_notion_page
    type: io.kestra.plugin.notion.page.Create
    apiToken: "{{ secret('NOTION_API_KEY') }}"
    parentPageId: "{{ secret('NOTION_PARENT_PAGE_ID') }}" # The ID of the Notion page where new pages should be created
    title: "Daily News Summary from AI"
    content: "{{ outputs.chat_completion.outputText }}"
    
  - id: send_slack_notification
    type: io.kestra.plugin.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK_URL') }}"
    messageText: "New Notion page created: {{ outputs.create_notion_page.url }}"

triggers:
  - id: daily_run
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 * * *"
    disabled: true


description: |
  Every day at 00:00 UTC, it:
    - Uses Perplexity (model: sonar) to compile a short markdown digest of the day’s top news
    - Creates a Notion page containing the generated summary
    - Sends a Slack notification with a direct link to the new Notion page
  The flow is configurable and suitable for both personal and team use. Provide the required API keys as secrets, adjust
  the Notion parent page/location, and tailor the prompt, schedule, or temperature as needed.

extend:
  title: Generate a Daily AI News Summary and Publish It to Notion with Slack Alerts
  description: |
    This blueprint demonstrates how to **automatically generate a daily news
    summary using AI**, publish it to **Notion**, and notify stakeholders via
    **Slack** when the digest is ready.

    It shows how to:

    1. Use an AI search and reasoning model to compile the most important news
       headlines for a specific location or audience.
    2. Generate a clean, readable summary with headlines and source links.
    3. Publish the generated news digest as a new page in Notion for long-term
       reference and collaboration.
    4. Send a Slack notification containing a direct link to the newly created
       Notion page.
    5. Schedule the entire process to run automatically on a daily basis.

    This pattern is ideal for **daily briefings**, **executive summaries**,
    **knowledge management**, and **team information sharing**, where curated
    news needs to be delivered consistently and stored in a central workspace.

    The automation can easily be adapted to different regions, topics, or
    audiences by modifying the AI prompt, making it suitable for internal
    newsletters, market monitoring, or competitive intelligence workflows.
  tags:
    - AI
  ee: false
  demo: false
  meta_description: |
    Automatically generate a daily AI-powered news digest, publish it to Notion,
    and notify Slack. A simple automation for daily briefings and knowledge
    sharing.
