id: airbyte-cloud-sync
namespace: company.team

tasks:
  - id: data_ingestion
    type: io.kestra.plugin.airbyte.cloud.jobs.Sync
    connectionId: ac127cf2-9ae3-4f9b-9dd0-e3a0944d1447
    token: "{{ secret('AIRBYTE_CLOUD_API_TOKEN') }}"

triggers:
  - id: every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"

extend:
  title: Run a Scheduled ETL Sync with Airbyte Cloud
  description: |
    This blueprint demonstrates how to **run a scheduled ETL data sync** using
    **Airbyte Cloud**, triggering a single connection on a recurring schedule.

    It performs the following actions:

    - Triggers an Airbyte Cloud sync for a specific connection.
    - Runs the sync automatically based on a CRON schedule.
    - Keeps ingestion logic simple and focused on a single data source.
    - Enables frequent or near-real-time data ingestion patterns.

    This pattern is commonly used for **ETL pipelines**, **incremental data
    ingestion**, and **operational analytics** where a single source needs to be
    refreshed regularly without coordinating multiple dependencies.

    Configuration:
      - Generate an Airbyte Cloud API key from the
        [Airbyte Cloud developer portal](https://portal.airbyte.com/apiKeys).
      - Store the API key securely as a secret (`AIRBYTE_CLOUD_API_TOKEN`).
      - Replace the `connectionId` with the Airbyte Cloud connection you want to
        sync.
      - Adjust the CRON schedule to control how frequently the ETL sync runs.

    This automation provides a reliable foundation for simple ETL workflows and
    can be combined with downstream transformations or analytics jobs as your
    data pipeline grows.
  tags:
    - Data
  ee: false
  demo: false
  meta_description: |
    Run a scheduled ETL sync with Airbyte Cloud to ingest data automatically on
    a recurring basis. A simple pattern for reliable data ingestion pipelines.
