id: airbyte-cloud-sync
namespace: company.team

tasks:
  - id: data_ingestion
    type: io.kestra.plugin.airbyte.cloud.jobs.Sync
    connectionId: ac127cf2-9ae3-4f9b-9dd0-e3a0944d1447
    token: "{{ secret('AIRBYTE_CLOUD_API_TOKEN') }}"

triggers:
  - id: every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"

extend:
  title: Trigger a single Airbyte Cloud sync on schedule
  description: |
    This flow will sync data using Airbyte Cloud. You can generate an API key in
    the [Airbyte’s Cloud developer portal](https://portal.airbyte.com/apiKeys).

    It's best to set the Airbyte Cloud API key as a secret, but you can also
    paste it into the flow in plain text during testing.
  tags:
    - Kestra
  ee: false
  demo: false
  meta_description: "This flow will sync data using Airbyte Cloud. "
