id: export_audit_logs_csv
namespace: company.team

tasks:
  - id: ship_audit_logs
    type: "io.kestra.plugin.ee.core.log.AuditLogShipper"
    lookbackPeriod: P1D
    logExporters:
      - id: file
        type: io.kestra.plugin.ee.core.log.FileLogExporter

  - id: convert_to_csv
    type: "io.kestra.plugin.serdes.csv.IonToCsv"
    from: "{{ outputs.ship_audit_logs.outputs.file.uris }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 10 * * *

extend:
  title: Stream kestra audit logs from a Kafka topic to BigQuery for analytics and
    troubleshooting
  description: |
    This flow shows how to export Kestra audit logs as CSV files.

    The flow is triggered every day at 10 AM UTC. You can customize the trigger
    by changing the cron expression, timezone and more. For more information
    about cron expressions, visit the [following
    documentation](https://kestra.io/docs/developer-guide/triggers/schedule).

  tags:
    - Kestra
  ee: true
  demo: false
  meta_description: This flow shows how to export Kestra audit logs CSV files.
