id: aws-log-shipper
namespace: system

tasks:
  - id: log_export
    type: io.kestra.plugin.ee.core.log.LogShipper
    logLevelFilter: INFO
    lookbackPeriod: P1D
    offsetKey: log_shipper_aws_cloudwatch_state
    delete: false
    logExporters:
      - id: aws_cloudwatch
        type: io.kestra.plugin.ee.aws.cloudwatch.LogExporter
        accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
        secretKeyId: "{{ secret('AWS_SECRET_KEY_ID') }}"
        region: "{{ vars.region }}"
        logGroupName: kestra
        logStreamName: kestra-log-stream

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"

extend:
  title: Ship Kestra logs to AWS CloudWatch
  description: |
    This system flow ships Kestra logs to AWS CloudWatch on a daily basis.
    
    It uses the `LogShipper` task to export logs and the `LogExporter` for AWS CloudWatch.
  tags:
    - System
  ee: true
  demo: false
  meta_description: Ship Kestra logs to AWS CloudWatch
