id: create-linear-issue-on-failure
namespace: system

tasks:
  - id: linear
    type: io.kestra.plugin.linear.issues.Create
    token: your_api_token
    team: MyTeamName
    title: Workflow failed
    description: "{{ trigger.executionId }} has failed on {{ taskrun.startDate }}.
      See the link below for more details"
    labels:
      - Bug
      - Workflow

triggers:
  - id: on_failure
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - FAILED
          - WARNING
      - type: io.kestra.plugin.core.condition.ExecutionNamespace
        namespace: company
        comparison: PREFIX

extend:
  title: Incident Management: Create Linear Issues Automatically When Kestra Workflows Fail
  description: |
    This system blueprint implements an **incident management and monitoring
    pattern** by automatically creating **Linear issues** whenever a Kestra
    workflow execution fails.

    It demonstrates how to:

    1. Monitor workflow executions globally using a system-level flow trigger.
    2. Automatically detect failed or warning executions across all namespaces
       with a specific prefix.
    3. Create structured issues in **Linear** containing execution metadata
       such as execution ID and start time.
    4. Centralize workflow incidents alongside product and engineering issues
       in Linear.
    5. Extend the flow with additional notifications, enrichment steps, or
       custom trigger conditions.

    This pattern is ideal for **incident tracking**, **operational monitoring**,
    and **platform reliability** workflows where failed executions must be
    surfaced quickly and consistently.

    You can customize this system flow by modifying the task, adding more tasks,
    or adjusting the trigger conditions. Read more about this pattern in the
    [Administrator
    Guide](https://kestra.io/docs/administrator-guide/monitoring).

    Example failure flow used to trigger this system flow:

    ```yaml
    id: failure_flow
    namespace: company.team

    tasks:
      - id: always_fails
        type: io.kestra.plugin.core.execution.Fail
    ```

    Whenever the `failure_flow` is executed and fails, this system blueprint
    automatically creates a corresponding issue in Linear.
  tags:
    - Infrastructure
    - System
  ee: false
  demo: false
  meta_description: |
    Automatically create Linear issues when Kestra workflows fail. An incident
    management and monitoring blueprint for tracking workflow execution failures.

