id: csv-duckdb-slack
namespace: company.team

tasks:
  - id: analyze_sales
    type: io.kestra.plugin.jdbc.duckdb.Queries
    sql: |
      INSTALL httpfs;

      LOAD httpfs;

      SELECT sum(total) as total, avg(quantity) as avg_quantity

      FROM
      read_csv_auto('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv',
      header=True);
    fetchType: FETCH

  - id: slack
    type: io.kestra.plugin.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK') }}"
    payload: |
      {"channel": "#reporting",
       "text": "Current Sales numbers: total sales is `${{ outputs.analyze_sales.rows[0].total }}` and average sales quantity is `{{ outputs.analyze_sales.rows[0].avg_quantity }}`"
      }

triggers:
  - id: every_monday
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 9 * * MON

extend:
  title: Run scheduled sales analytics on CSV data with DuckDB and post results to Slack
  description: |
    This automation runs a **scheduled sales analysis directly on a CSV file**
    using DuckDB and publishes the results to Slack for easy visibility by
    business and analytics teams.

    On a weekly basis, it:
      - Queries a remote CSV file without loading it into a database
      - Calculates key metrics such as total revenue and average order quantity
      - Sends a formatted summary message to a Slack channel
      - Runs automatically every Monday morning

    This pattern is well suited for:
      - Lightweight analytics without maintaining a data warehouse
      - Automated business reporting in Slack
      - Monitoring KPIs from CSV or flat-file data sources
      - Replacing manual spreadsheet checks with scheduled insights
      - Fast prototyping of analytics workflows

    DuckDB enables fast, in-place SQL analytics on external files, making it
    ideal for reporting use cases where data lives in object storage, HTTP
    endpoints, or shared datasets.

    If you use [MotherDuck](https://motherduck.com/), you can run the same query
    against a cloud-hosted DuckDB database by configuring a service token as a
    secret and setting the database URL:

    ```yaml
      - id: analyze_sales
        type: io.kestra.plugin.jdbc.duckdb.Queries
        url: "jdbc:duckdb:md:my_db?motherduck_token={{ secret('MOTHERDUCK_TOKEN') }}"
    ```

    This allows you to scale from local CSV analytics to cloud-backed DuckDB
    without changing the SQL logic.
  tags:
    - Data
  ee: false
  demo: false
  meta_description: |
    Schedule CSV analytics with DuckDB and automatically send sales metrics to
    Slack. Run SQL directly on CSV files and deliver weekly business reports
    without a database.

