id: daily-shopify-stripe-summary
namespace: company.team

tasks:
  - id: get_balance
    type: io.kestra.plugin.stripe.balance.Retrieve
    apiKey: "{{ secret('STRIPE_API_KEY') }}"

  - id: list_orders
    type: io.kestra.plugin.shopify.orders.List
    storeDomain: my-store.myshopify.com
    accessToken: "{{ secret('SHOPIFY_ACCESS_TOKEN') }}"

  - id: update_notion
    type: io.kestra.plugin.notion.page.Update
    apiToken: "{{ secret('NOTION_API_TOKEN') }}"
    pageId: "12345678-1234-1234-1234-123456789abc"
    content: |
      # Daily Update

      Stripe balance:
      {{ outputs.get_balance }}

      Shopify orders:
      {{ outputs.list_orders }}

  - id: send_slack_message
    type: io.kestra.plugin.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK') }}"
    payload: |
      {
        "text": "Daily update completed for flow {{ flow.namespace }}.{{ flow.id }} (execution {{ execution.id }})"
      }

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 * * *"

extend:
  title: Daily Shopify orders and Stripe balance to Notion with Slack update
  description: |
    This flow runs once every 24 hours and:
    - Retrieves the current Stripe balance
    - Lists Shopify orders
    - Updates a Notion page with the balance and the order list
    - Sends a Slack message after the Notion page is updated
  tags:
    - Kestra
    - Shopify
    - Stripe
    - Notion
    - Slack
    - Daily
  ee: false
  demo: false
  meta_description: Run daily to fetch Shopify orders and Stripe balance, update a Notion page, and send a Slack status message.
