id: dlt-elt-chess-api-to-duckdb
namespace: company.team

tasks:
  - id: chess_api_to_duckdb
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: python:slim
    beforeCommands:
      - pip install dlt[duckdb]
    script: |
      import dlt
      import requests

      pipeline = dlt.pipeline(
          pipeline_name='chess_pipeline',
          destination='duckdb',
          dataset_name='player_data'
      )
      data = []
      for player in ['magnuscarlsen', 'rpragchess']:
          response = requests.get(f'https://api.chess.com/pub/player/{player}')
          response.raise_for_status()
          data.append(response.json())
      # Extract, normalize, and load the data
      pipeline.run(data, table_name='player')

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: true
    cron: 0 9 * * *

extend:
  title: Run a scheduled ELT pipeline in Python: extract Chess.com API data and load it into DuckDB with dltHub
  description: |
    Build a lightweight **ELT pipeline** in Python that pulls player profiles from the Chess.com REST API and loads them into **DuckDB** using **dltHub (dlt)** — ideal for scheduled ingestion, prototyping, and local analytics.

    **What this automation does:**
    - Extracts JSON data from the Chess.com public API for a list of players.
    - Uses `dlt.pipeline()` to normalize the JSON into a relational table (`player`) automatically.
    - Loads the result into a DuckDB destination dataset (`player_data`) for fast SQL querying and local development.

    **Why dlt + DuckDB works well here:**
    - dlt handles schema inference and normalization, so you don’t have to hand-write transformations for nested JSON.
    - DuckDB keeps everything portable (single file / local execution), making it perfect for demos, tests, and analyst workflows.

    **Scheduling:**
    - A daily schedule trigger is included (09:00), but disabled by default so you can enable it when you’re ready.

    **Tip:**
    - To ingest more players, extend the list in the Python script or replace it with an input-driven list for dynamic ingestion.
  tags:
    - Data
  ee: false
  demo: false
  meta_description: Run a scheduled Python ELT pipeline that extracts Chess.com API data and loads it into DuckDB using dltHub, with automatic JSON normalization and schema handling.

