id: failure-alert-teams
namespace: system

tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.teams.TeamsExecution
    url: "{{ secret('TEAMS_WEBHOOK') }}"
    executionId: "{{ trigger.executionId }}"

triggers:
  - id: on_failure
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - FAILED
          - WARNING

extend:
  title: Set up alerts for failed workflow executions using Microsoft Teams
  description: |
    This system flow will help you set up alerts for failed workflow executions.
    Using this pattern, you can manage alerts on failure in one place.

    Here, we send a message to a Microsoft Teams channel when any workflow
    execution fails. 

    You can further customize that system flow by modifying the `TeamsExecution`
    task, or by adding more tasks to the flow.

    Additionally, you can restrict the flow to only send alerts for specific
    namespaces by adding an `ExecutionNamespaceCondition` to the trigger. You
    can read more about that in the [Administrator
    Guide](https://kestra.io/docs/administrator-guide/monitoring).
  tags:
    - Core
  ee: false
  demo: false
  meta_description: Set up alerts for failed workflow executions using Microsoft
    Teams and system flows in Kestra.
