id: purge_kv_store
namespace: system

tasks:
  - id: purge_kv
    type: io.kestra.plugin.core.kv.PurgeKV
    description: Remove key-value (KV) entries from Kestra’s internal storage every day at 12AM.
    expiredOnly: true 
    namespaces:
      - system
      - company
    includeChildNamespaces: true # Whether to include sub-namespaces of the matched namespace(s).
    
triggers:
  - id: daily_midnight_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 * * *"

extend:
  title: Purge KV Store
  description: |
    Purge key-value entries from Kestra’s internal storage across namespaces, with optional filters for keys and namespaces.
  tags:
    - Kestra
    - System
  ee: false
  demo: true
  meta_description: Purge key-value entries from Kestra’s internal storage across namespaces, with optional filters for keys and namespaces.
