id: purge_kv_store
namespace: system

tasks:
  - id: purge_kv
    type: io.kestra.plugin.core.kv.PurgeKV
    description: Remove key-value (KV) entries from Kestra’s internal storage every day at 12AM.
    expiredOnly: false # When true (default), only expired keys are removed. Setting to false removes all keys.
    namespaces:        # Optional: list of namespaces from which to purge keys.
                       # Cannot be used together with `namespacePattern`.
                       # If not set, all namespaces are included.
    namespacePattern: "*" # Optional: glob pattern to match namespaces (e.g., "AI_*").
                          # Cannot be used together with `namespaces`.
                          # Default: all namespaces.
    includeChildNamespaces: true # Whether to include sub-namespaces of the matched namespace(s).
                                 # Default: true.
    keyPattern: "*" # Optional: glob pattern to match keys (e.g., "AI_*").
                    # Default: all keys.
triggers:
  - id: daily_midnight_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 * * *"

extend:
  title: Purge KV Store
  description: |
    Purge key-value entries from Kestra’s internal storage across namespaces, with optional filters for keys and namespaces.
  tags:
    - Kestra
    - System
  ee: false
  demo: true
  meta_description: Purge key-value entries from Kestra’s internal storage across namespaces, with optional filters for keys and namespaces.
