id: namespace-sync-from-git
namespace: system

tasks:
  - id: sync
    type: io.kestra.plugin.git.NamespaceSync
    namespace: system
    sourceOfTruth: GIT
    whenMissingInSource: DELETE
    protectedNamespaces:
      - system
    url: https://github.com/example_org/example_repo
    username: "{{ secret('GITHUB_USERNAME') }}"
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    branch: main
    gitDirectory: example_directory

triggers:
  - id: every_15_minutes
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"

extend:
  title: Sync namespace resources from Git at regular intervals
  description: |
    This flow will sync namespace resources from Git to Kestra every 15 minutes.

    We will be using NamespaceSync task to sync namespace resources from Git to Kestra.

  tags:
    - Kestra
    - Git
    - System
  ee: false
  demo: false
  meta_description: Sync namespace resources from Git to Kestra at regular intervals
