id: parametrized-flow-with-multiple-schedules
namespace: company.team

inputs:
  - id: user
    type: STRING
    prefill: Data Engineer
    required: false

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs.user }} from Kestra!

triggers:
  - id: quarter_hourly
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: true
    cron: "*/15 * * * *"
    inputs:
      name: user

  - id: every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: true
    cron: "*/1 * * * *"
    inputs:
      name: user
      value: custom value

extend:
  title: Parametrized workflow with multiple schedules
  description: >
    This flow takes a runtime-specific input and uses it to log a message to the
    console.

    The flow has two scheduled attached to it: 
    - one that runs every 15 minutes with the default input parameter value
    - another one that runs every 1 minute with a custom input parameter value

    Note that both schedules are currently disabled. 

    To start scheduling the flow, set the `disabled` property to `false` or
    delete that property entirely.
  tags:
    - Kestra
  ee: false
  demo: true
  meta_description: This flow takes a runtime-specific input and uses it to log a
    message to the console.
