id: repo-ingestion-controller
namespace: company.team

description: |
  **Repository Batch Ingestion Controller**
  
  Orchestration workflow that manages automated documentation synchronization across multiple GitHub repositories. Operates as the master controller that triggers the `single-repo-ingestion` subflow for each tracked repository.
  
  **Key Features:**
  - **Batch Processing**: Processes all repositories with tracking enabled from MongoDB
  - **Concurrent Execution**: Handles up to 3 repositories simultaneously for efficiency
  - **Selective Processing**: Only processes repositories where `tracking_enabled: true`
  - **Subflow Orchestration**: Triggers `single-repo-ingestion` workflow for each repository
  - **Automated Scheduling**: Runs daily at midnight via cron trigger
  - **Error Propagation**: Transmits failures from subflows for proper error handling
  
  **Process Flow:**
  1. Fetches all repository records from MongoDB collection
  2. Filters repositories with tracking enabled
  3. Concurrently executes `single-repo-ingestion` subflow for each repository
  4. Waits for subflow completion and handles any failures
  

tasks:
  - id: fetch_ingested_repo
    type: io.kestra.plugin.mongodb.Find
    connection:
      uri: "{{secret('MONGO_URI')}}"
    database: "{{secret('DB')}}"
    collection: "{{secret('COLLECTION_NAME')}}"
    projection:
      _id: 0
      files: 0

  - id: for_each_repo
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 3
    values: "{{ outputs.fetch_ingested_repo.rows }}"
    tasks:
      - id: if-tracking-changes
        type: io.kestra.plugin.core.flow.If
        condition: "{{ json(taskrun.value).tracking_enabled == true }}"
        then:
          - id: trigger_repo_ingestion
            type: io.kestra.plugin.core.flow.Subflow
            namespace: company.team
            flowId: single-repo-ingestion
            wait: true
            transmitFailed: true
            inputs:
              repo_name: "{{ json(parent.taskrun.value).repo_name }}"
              branch: "{{ json(parent.taskrun.value).branch }}"

triggers:
  - id: schedule_ingestion
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"