id: splunk-log-shipper
namespace: system

tasks:
  - id: log_export
    type: io.kestra.plugin.ee.core.log.LogShipper
    logLevelFilter: INFO
    lookbackPeriod: P1D
    offsetKey: logShipperOffset
    delete: false
    logExporters:
      - id: SplunkLogExporter
        type: io.kestra.plugin.ee.splunk.LogExporter
        host: https://example.splunkcloud.com:8088
        token: "{{ secret('SPLUNK_API_KEY') }}"

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"

extend:
  title: Ship Kestra logs to Splunk
  description: |
    This system flow ships Kestra logs to Splunk on a daily basis.
    
    It uses the `LogShipper` task to export logs and the `LogExporter` for Splunk.
  tags:
    - Infra
    - Core
  ee: true
  demo: false
  meta_description: Ship Kestra logs to Splunk
