id: sync-from-git
namespace: system

tasks:
  - id: sync_flows
    type: io.kestra.plugin.git.SyncFlows
    gitDirectory: flows
    targetNamespace: git
    includeChildNamespaces: true
    delete: true
    url: https://github.com/kestra-io/flows
    branch: main
    username: git_username
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    dryRun: true

  - id: sync_namespace_files
    type: io.kestra.plugin.git.SyncNamespaceFiles
    namespace: prod
    gitDirectory: _files
    delete: true
    url: https://github.com/kestra-io/flows
    branch: main
    username: git_username
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    dryRun: true

triggers:
  - id: every_full_hour
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 * * * *"

extend:
  title: Sync code from Git at regular intervals
  description: |
    This flow will sync code from Git every full hour.

    We will be using SyncFlows and SyncNamespaceFiles task to sync flows and
    namespace files respectively.
  tags:
    - Kestra
    - Git
    - System
  ee: false
  demo: false
  meta_description: Sync flows and namespace files from Git at regular intervals
