id: tenant-sync-from-git
namespace: system

tasks:
  - id: tenant_sync
    type: io.kestra.plugin.git.TenantSync
    sourceOfTruth: GIT
    whenMissingInSource: DELETE
    protectedNamespaces:
      - system
    url: https://github.com/example_org/example_repo
    username: "{{ secret('GITHUB_USERNAME') }}"
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    branch: main
    gitDirectory: example_directory
    kestraUrl: "http://localhost:8080"
    auth:
      username: "{{ secret('KESTRA_USERNAME') }}" 
      password: "{{ secret('KESTRA_PASSWORD') }}"

triggers:
  - id: every_15_minutes
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"

extend:
  title: Sync tenant resources at regular intervals
  description: |
    This flow will sync all namespaces, flows, files, and dashboards between Git and Kestra every 15 minutes. It's a unidirectional sync from Git to Kestra.

    We will be using TenantSync task to sync all namespaces, flows, files, and dashboards between Git and Kestra.

  tags:
    - Kestra
    - Git
    - System
  ee: false
  demo: false
  meta_description: Sync all namespaces, flows, files, and dashboards between Git and Kestra at regular intervals
